// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vytqkezseosvjphkeavg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5dHFrZXpzZW9zdmpwaGtlYXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODk1OTQsImV4cCI6MjA2NjQ2NTU5NH0.SowptVzPUoBK4LskZuv76fGydKzCvMOLoE1yuOXZgq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);